drop table EDUCATION if exists;
drop table STUDENT if exists;
create table EDUCATION (EDUCATION_ID bigint generated by default as identity, DEGREE_CODE varchar(255), DEGREE_YR integer, INSTITUTION varchar(255), STUDENT_ID bigint, primary key (EDUCATION_ID));
create table STUDENT (STUDENT_ID bigint generated by default as identity, FNAME varchar(255), LNAME varchar(255), primary key (STUDENT_ID));
alter table EDUCATION add constraint FK94C3778838927B8D foreign key (STUDENT_ID) references STUDENT;