drop table EDUCATION if exists;
drop table MEDICAL if exists;
drop table PUBLICATION if exists;
drop table STUDENT if exists;

create table EDUCATION (EDUCATION_ID bigint generated by default as identity, DEGREE_CODE varchar(255), DEGREE_YR integer, INSTITUTION varchar(255), STUDENT_ID bigint, primary key (EDUCATION_ID));
create table STUDENT (STUDENT_ID bigint generated by default as identity, FNAME varchar(255), LNAME varchar(255), primary key (STUDENT_ID));
alter table EDUCATION add constraint FK94C3778838927B8D foreign key (STUDENT_ID) references STUDENT;

create table MEDICAL (MEDICAL_ID bigint generated by default as identity, DEGREE_CODE varchar(255), DEGREE_YR varchar(255), INST_NAME varchar(255), STUDENT_ID bigint, primary key (MEDICAL_ID));
create table PUBLICATION (PUB_ID bigint generated by default as identity, AUTHOR varchar(255), NAME varchar(255), NO_PAGES integer, PUB_DATE timestamp, PUB_TYPE varchar(255), STUDENT_ID bigint, primary key (PUB_ID));
alter table MEDICAL add constraint FK62DEA67138927B8D foreign key (STUDENT_ID) references STUDENT;
alter table PUBLICATION add constraint FK400F360C38927B8D foreign key (STUDENT_ID) references STUDENT;